poisson_parameters:
  male:
    15-55 : 0.25
    55-100 : 0.15
  female:
    15-55 : 0.25
    55-100: 0.15
  neighbours_to_consider: 2
  maximum_distance: 5
  weekend_boost: 2.0
  drags_household_probability: 2.0


#source
#https://runrepeat.com/gym-membership-statistics
#~50% are female members
#peak around 18-55
#In general, with other articles
#about every 5th person has a gym membership
