testing:
  1:
    start_time: 2020-03-01
    end_time: 2020-03-12
    specificity: 1
    primary_activity:
      - company
      - school
    frequency:
      Saturday: False
      Sunday: False
      Monday: True
      Tuesday: True
      Wednesday: True
      Thursday: True
      Friday: True
    compliance: 0.95 # to be discussed
      
hospitalisation:
  start_time: 1000-01-01
  end_time: 9999-01-01

severe_symptoms_stay_home:
  start_time: 1000-01-01
  end_time: 9999-01-01

regional_compliance:
  1:
    start_time: 1000-07-04
    end_time: 9999-12-01
    compliances_per_region:
      Baden-Wuerttemberg: 1.
      Bayern: 1.
      Berlin: 1.
      Brandenburg: 1.
      Bremen: 1.
      Hamburg: 1.
      Hessen: 1.
      Mecklenburg-Vorpommern: 1.
      Niedersachsen: 1.
      Nordrhein-Westfalen: 1.
      Rheinland-Pfalz: 1.
      Saarland: 1.
      Sachsen: 1.
      Sachsen-Anhalt: 1.
      Schleswig-Holstein: 1.
      Thueringen: 1.

tiered_lockdown:
  1:
    start_time: 2020-12-03
    end_time: 9999-12-01
    tiers_per_region:
      Baden-Wuerttemberg: 1.
      Bayern: 1.
      Berlin: 1.
      Brandenburg: 1.
      Bremen: 1.
      Hamburg: 1.
      Hessen: 1.
      Mecklenburg-Vorpommern: 1.
      Niedersachsen: 1.
      Nordrhein-Westfalen: 1.
      Rheinland-Pfalz: 1.
      Saarland: 1.
      Sachsen: 1.
      Sachsen-Anhalt: 1.
      Schleswig-Holstein: 1.
      Thueringen: 1.

      hospitalisation:
    start_time: 1000-01-01
    end_time: 9999-01-01

limit_long_commute:
    #prevents people that have their workplace
    #far away from their homes of commuting daily.
    #does not apply to Germany
    start_time: 1000-01-01
    end_time: 9999-01-01
    apply_from_distance: 2000
    going_to_work_probability: 1.0 #every day

quarantine:
    1:
        n_days: 14 # for the symptomatic person - from BfG
        n_days_household: 14 # for the housemates
        compliance: 0.95 
        household_compliance: 0.9
        start_time: 2020-02-26 
        end_time: 2020-03-22 
    2:
        n_days: 10 # for the symptomatic person
        n_days_household: 14 # for the housemates
        compliance: 0.95 # for the symptomatic individual - needs to be checked
        household_compliance: 0.9
        start_time: 2020-03-22
        end_time: 2021-07-04

shielding:
    1:
        min_age: 60
        compliance: 0.6
        start_time: 2020-03-01 
        end_time: 2020-03-22
    2:
        min_age: 60
        compliance: 0.5
        start_time: 2020-03-22
        end_time: 2020-05-06
    3:
        min_age: 60
        compliance: 0.6
        start_time: 2020-05-06
        end_time: 2020-10-28
    4:
        min_age: 60
        compliance: 0.5
        start_time: 2020-10-28
        end_time: 2021-03-01

close_companies:
    1:
        start_time: 2020-03-08
        end_time: 2020-03-22
        full_closure: False 
        avoid_work_probability: 0.04 # prob of being in homeoffice if still working
        furlough_probability: 0.04 # prob of being furloughed/business closed
        key_probability: 0.19 # prob of being a key worker
    2:
        start_time: 2020-03-22
        end_time: 2020-05-31
        full_closure: False 
        avoid_work_probability: 0.27
        furlough_probability: 0.30
        key_probability: 0.19
    3:
        start_time: 2020-06-01
        end_time: 2020-06-30
        full_closure: False 
        avoid_work_probability: 0.16
        furlough_probability: 0.04
        key_probability: 0.19
    4:
        start_time: 2020-07-01
        end_time: 2020-10-31
        full_closure: False 
        avoid_work_probability: 0.15 #by interpolation
        furlough_probability: 0.04
        key_probability: 0.19
    5:
        start_time: 2020-11-01
        end_time: 2020-11-30
        full_closure: False 
        avoid_work_probability: 0.14
        furlough_probability: 0.2
        key_probability: 0.19
    6:
        start_time: 2020-12-01
        end_time: 2020-12-31
        full_closure: False 
        avoid_work_probability: 0.17
        furlough_probability: 0.34
        key_probability: 0.19
    7:
        start_time: 2021-01-01
        end_time: 2021-01-31
        full_closure: False 
        avoid_work_probability: 0.24
        furlough_probability: 0.34
        key_probability: 0.19

social_distancing:
    1: 
        start_time: 2020-03-08
        end_time: 2020-03-22 
        beta_factors:
            box: 0.95
            pub: 0.95
            grocery: 0.95
            cinema: 0.95
            city_transport: 0.95
            inter_city_transport: 0.95
            hospital: 0.95
            care_home: 0.95
            company: 0.95
            school: 0.95
            household: 1.0
            university: 0.95
            household_visits: 0.95

    2:
        start_time: 2020-03-22
        end_time: 2020-05-06
        beta_factors:
            box: 0.75
            pub: 0.75
            grocery: 0.75
            cinema: 0.75
            city_transport: 0.75
            inter_city_transport: 0.75
            hospital: 0.75
            care_home: 0.75
            company: 0.75
            school: 0.75
            household: 1.0
            university: 0.75
    3:
        start_time: 2020-05-06
        end_time: 2020-10-07
        beta_factors:
            box: 0.786
            pub: 0.786
            grocery: 0.786
            cinema: 0.786
            city_transport: 0.786
            inter_city_transport: 0.786
            hospital: 0.786
            care_home: 0.786
            company: 0.786
            school: 0.786
            household: 1.0
            university: 0.786
            household_visits: 0.5
    4:
        start_time: 2020-10-07 
        end_time: 2021-10-28
        beta_factors:
            box: 0.875
            pub: 0.875
            grocery: 0.875
            cinema: 0.875
            city_transport: 0.875
            inter_city_transport: 0.875
            hospital: 0.875
            care_home: 0.875
            company: 0.875
            school: 0.875
            household: 1.0
            university: 0.875
            household_visits: 0.5
    5:
        start_time: 2020-10-28
        end_time: 2020-11-25
        beta_factors:
            box: 0.75
            pub: 0.75
            grocery: 0.75
            cinema: 0.75
            city_transport: 0.75
            inter_city_transport: 0.75
            hospital: 0.75
            care_home: 0.75
            company: 0.75
            school: 0.75
            household: 1.0
            university: 0.75
            household_visits: 0.5

    6:
        start_time: 2020-11-25
        end_time: 2020-12-13
        beta_factors:
            box: 0.875
            pub: 0.875
            grocery: 0.875
            cinema: 0.875
            city_transport: 0.875
            inter_city_transport: 0.875
            hospital: 0.875
            care_home: 0.875
            company: 0.875
            school: 0.875
            household: 1.0
            university: 0.875
            household_visits: 0.5
            
    7:
        start_time: 2020-12-13
        end_time: 2021-03-01
        beta_factors:
            box: 0.875
            pub: 0.875
            grocery: 0.875
            cinema: 0.875
            city_transport: 0.875
            inter_city_transport: 0.875
            hospital: 0.875
            care_home: 0.875
            company: 0.875
            school: 0.875
            household: 1.0
            university: 0.875
            household_visits: 0.5

mask_wearing:
    1: 
        start_time: 2020-03-08
        end_time: 2020-03-22
        compliance: 0.04 # overall mask wearing compliance
        beta_factor: 0.5 # overall beta reducion if mask wearing
        mask_probabilities: # probability of where it is worn
            box: 1.
            pub: 0.
            grocery: 0.04
            cinema: 0.
            inter_city_transport: 1.
            city_transport: 1.
            hospital: 1.
            care_home: 1.
            company: 0.04
            school: 0.
            household: 0.
            university: 0.5
    2: 
        start_time: 2020-03-22
        end_time: 2020-04-27
        compliance: 0.04
        beta_factor: 0.5
        mask_probabilities:
            box: 1.
            pub: 0.
            grocery: 0.04
            cinema: 0.
            inter_city_transport: 1.
            city_transport: 1.
            hospital: 1.
            care_home: 1.
            company: 0.04
            school: 0.
            household: 0.
            university: 0.04
    3: 
        start_time: 2020-04-27
        end_time: 2020-05-06
        compliance: 0.95
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 1.
            inter_city_transport: 1.
            city_transport: 1.
            hospital: 1.
            care_home: 1.
            company: 0.5
            school: 0.5
            household: 0.
            university: 0.5
    4: 
        start_time: 2020-05-06
        end_time: 2020-10-28
        compliance: 0.9
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 1.
            inter_city_transport: 1.
            city_transport: 1.
            hospital: 1.
            care_home: 1.
            company: 0.5
            school: 0.5
            household: 0.
            university: 0.5
    5: 
        start_time: 2020-10-28
        end_time: 2020-12-13
        compliance: 0.95
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 1.
            inter_city_transport: 1.
            city_transport: 1.
            hospital: 1.
            care_home: 1.
            company: 0.5
            school: 0.5
            household: 0.
            university: 0.5
    6: 
        start_time: 2020-12-13
        end_time: 2021-01-25
        compliance: 0.95
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 1.
            inter_city_transport: 1.
            city_transport: 1.
            hospital: 1.
            care_home: 1.
            company: 0.5
            school: 1.
            household: 0.
            university: 0.5
    7: 
        start_time: 2021-01-25
        end_time: 2020-03-01
        compliance: 0.95
        beta_factor: 0.5
        mask_probabilities: 
            box: 1.
            pub: 0.
            grocery: 1.
            cinema: 1.
            inter_city_transport: 1.
            city_transport: 1.
            hospital: 1.
            care_home: 1.
            company: 0.5
            school: 1.
            household: 0.
            university: 0.5

close_leisure_venue:
    1:
        start_time: 2020-03-22
        end_time: 2020-05-06 
        venues_to_close: ['pub', 'cinema', 'care_home_visit']
    2:
        start_time: 2020-10-28
        end_time: 2021-03-01 
        venues_to_close: ['pub', 'cinema', 'care_home_visit'] 

change_leisure_probability:
    1:
        start_time: 2020-03-22
        end_time: 2020-05-06
        leisure_poisson_parameters:
            household_visits:
                men: 
                    0-64: 0.1
                    65-100: 0.05
                women: 
                    0-64: 0.1
                    65-100: 0.05
            care_home_visits:
                men:
                    0-100: 0.05
                women:
                    0-100: 0.05
    2:
        start_time: 2020-05-06
        end_time: 2020-10-31
        leisure_poisson_parameters:
            household_visits:
                men: 
                    0-64: 0.25
                    65-100: 0.125
                women: 
                    0-64: 0.25
                    65-100: 0.125
            care_home_visits:
                men:
                    0-100: 0.05
                women:
                    0-100: 0.05
    3:
        start_time: 2020-11-01
        end_time: 2020-12-01
        leisure_poisson_parameters:
            household_visits:
                men: 
                    0-64: 0.2
                    65-100: 0.2
                women: 
                    0-64: 0.2
                    65-100: 0.2
            care_home_visits:
                men:
                    0-100: 0.05
                women:
                    0-100: 0.05
    4:
        start_time: 2020-12-01
        end_time: 2021-02-28
        leisure_poisson_parameters:
            household_visits:
                men: 
                    0-64: 0.07
                    65-100: 0.07
                women: 
                    0-64: 0.07
                    65-100: 0.07
            care_home_visits:
                men:
                    0-100: 0.05
                women:
                    0-100: 0.05
    5:
        start_time: 2021-03-01
        end_time: 2020-03-31
        leisure_poisson_parameters:
            household_visits:
                men: 
                    0-64: 0.10
                    65-100: 0.10
                women: 
                    0-64: 0.10
                    65-100: 0.10
            care_home_visits:
                men:
                    0-100: 0.05
                women:
                    0-100: 0.05

close_schools:
    1:
        start_time: 2020-03-16 #source RKI
        end_time: 2020-06-01
        years_to_close: all
        full_closure: False
    2:
        start_time: 2020-06-01
        end_time: 2020-06-11
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.125
        full_closure: False
    3:
        start_time: 2020-06-11
        end_time: 2020-06-18
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.195
        full_closure: False
    4:
        start_time: 2020-06-18
        end_time: 2020-06-25
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.253
        full_closure: False
    5:
        start_time: 2020-06-25
        end_time: 2020-07-02
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.312
        full_closure: False
    6:
        start_time: 2020-07-02
        end_time: 2020-07-16
        years_to_close: [0,1,2,7,8,9,12,13,14,15,16,17,18,19]
        attending_compliance: 0.37 
        full_closure: False
    7:
        start_time: 2020-07-16
        end_time: 2020-09-01
        years_to_close: all
        full_closure: False
    8:
        start_time: 2020-10-26
        end_time: 2020-10-31
        years_to_close: all
        full_closure: False
    9:
        start_time: 2020-12-13
        end_time: 2021-01-03
        years_to_close: all
        full_closure: True

close_universities:
    1:
        start_time: 2020-03-17 #based on JGU, but varies by region
        end_time: 2020-08-01
    2:
        start_time: 2020-12-13
        end_time: 2021-03-01
