# seats per passenger
# TODO: use real data
seats_per_passenger:
  Frankfurt (Main): 1
  Köln: 1
  Berlin: 1
  Hamburg: 1
  München: 1
  Stuttgart: 1
  Düsseldorf: 1
  Duisburg: 1
  Dortmund: 1
  Mannheim: 1
  Hannover: 1
  Nürnberg: 1
  Essen: 1
  Bremen: 1
  Leipzig: 1
