age_range: [0,19] # numbers correspond to age groups defined by NOMIS dataset.
mandatory_age_range: [5,18]
neighbour_schools: 10
sector: 'P'            # NOMIS name convention
sub_sector: ["teacher_secondary", "teacher_primary"]
# ratios source https://www.deutschlandinzahlen.de/tab/deutschland/bildung/schule/allgemeinbildende/schueler-je-lehrer-allgemeinbildende-schulen
teacher_student_ratio_primary: 16
teacher_student_ratio_secondary: 13
teacher_min_age: 21
max_classroom_size: 40 
