age_range: [18, 64]
sub_sector_ratio:
  P:  # education
    m: 0.02492507  # male, Wert laut research ca 1.8% zusammen
    f: 0.02726422  # female
  Q:  # healthcare
    m: 0.0163705
    f: 0.0507218

sub_sector_distr:
  P:
    label: ["teacher_secondary", "teacher_primary"]
    m: [0.7, 0.3]
    f: [0.7, 0.3]
  Q:
    label: ["doctor", "nurse"]
    m: [0.65350126, 0.34649874]
    f: [0.16103136, 0.83896864]

# home = work from home
# bind = send to random SuperArea within simulated geography
non_geographical_work_location:
  OD0000001: "home"
  OD0000002: "home"
  OD0000003: "bind"
  OD0000004: "bind"
