number_of_inter_city_stations: # each city also acts like an station for internal commuters.
  "Frankfurt am Main": 4
  "Koeln": 4
  "Berlin": 4
  "Hamburg": 4
  "Muenchen": 4
  "Stuttgart": 4
  "Duesseldorf": 4
  "Duisburg": 4
  "Dortmund": 4
  "Mannheim": 4
  "Hannover": 4
  "Nuernberg": 4
  "Essen": 4
  "Bremen": 4
  "Leipzig": 4

  # data from https://de.wikipedia.org/wiki/Bahnhof#Meistfrequentierte_Fernbahnh%C3%B6fe_in_Deutschland 01.09.2021


